export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
        "arcadia-red": "#902424",
        "white": "#FAFAFA",
        "dark-gray": "#333333",
        "black": "#000000",
        "light-white": "FAFAFA",
        "light-gray": "#f4f4f4",
        "grey": '#D4D4D8',
        "arcadia-black": '#18181B',
        "yellow": '#e8d08d',
        "orange": "#ff9800",
        "red": '#de6262',
        "bright-yellow": '#EEBA33',
        "dark-yellow": '#FFFF9F',
        "green" : '#8fd28f',
        "arcadia-yellow" : '#E9D08E',
        "dark-grey" : '#71717A',
        "silver" : '#F4F4F5',
        "a-t-red" : '#902424',
        "dark-blue" : '#0096C7',
        "light-blue" : '#48CAE4',
        "dark-green" : '#234F1E',
        "pastel-yellow" : '#FDFD96',
        "ongoing" : '#FFB200',
        "resolved" : '#118B50',
        "intended" : '#A31D1D',
    },
    extend: {
      fontFamily: {
        'Zen': ['"Zen Kaku Gothic Antique"', '"Zen Kaku Gothic New"', 'sans-serif'],
        'ZenSerif': ['"Zen Antique"', 'serif'],
      },
    }, 
  },
  plugins: [],
} 
