export const locClassifications = {
    "A": "General Works",
    "B": "Philosophy, Psychology, Religion",
    "C": "Auxiliary Sciences of History",
    "D": "World History",
    "E": "History of the Americas",
    "F": "History of the Americas",
    "G": "Geography, Anthropology, Recreation",
    "H": "Social Sciences",
    "J": "Political Science",
    "K": "Law",
    "L": "Education",
    "M": "Music",
    "N": "Fine Arts",
    "P": "Language and Literature",
    "Q": "Science",
    "R": "Medicine",
    "S": "Agriculture",
    "T": "Technology",
    "U": "Military Science",
    "V": "Naval Science",
    "Z": "Bibliography. Library Science. Information Resources (General)",
};

export const locSubclassifications = {
    // Class A: General Works
    "AC": "Collections. Series. Collected works",
    "AE": "Encyclopedias",
    "AG": "Dictionaries and other general reference works",
    "AI": "Indexes",
    "AM": "Museums. Collectors and collecting",
    "AN": "Newspapers",
    "AP": "Periodicals",
    "AS": "Academies and learned societies",
    "AY": "Yearbooks. Almanacs. Directories",
    "AZ": "History of scholarship. The humanities",

    // Class B: Philosophy, Psychology, Religion
    "B": "Philosophy (General)",
    "BC": "Logic",
    "BD": "Speculative philosophy",
    "BF": "Psychology",
    "BH": "Aesthetics",
    "BJ": "Ethics",
    "BL": "Religions. Mythology. Rationalism",
    "BM": "Judaism",
    "BP": "Islam. Bahaism. Theosophy, etc.",
    "BQ": "Buddhism",
    "BR": "Christianity",
    "BS": "The Bible",
    "BT": "Doctrinal theology",
    "BV": "Practical theology",
    "BX": "Christian denominations",

    // Class C: Auxiliary Sciences of History
    "C": "Auxiliary Sciences of History (General)",
    "CA": "Archival science", // Formerly used, now often Z665
    "CB": "History of civilization",
    "CC": "Archaeology",
    "CD": "Diplomatics. Archives. Seals",
    "CE": "Technical chronology. Calendar",
    "CJ": "Numismatics",
    "CN": "Inscriptions. Epigraphy",
    "CR": "Heraldry",
    "CS": "Genealogy",
    "CT": "Biography",

    // Class D: World History
    "D": "History (General)",
    "DA": "Great Britain",
    "DAW": "Central Europe",
    "DB": "Austria. Liechtenstein. Hungary. Czechoslovakia",
    "DC": "France. Andorra. Monaco",
    "DD": "Germany",
    "DE": "Graeco-Roman world",
    "DF": "Greece",
    "DG": "Italy. Malta",
    "DH": "Low Countries. Benelux Countries",
    "DJ": "Netherlands (Holland)",
    "DJK": "Eastern Europe (General)",
    "DK": "Russia. Soviet Union. Former Soviet Republics",
    "DL": "Northern Europe. Scandinavia",
    "DP": "Spain. Portugal",
    "DQ": "Switzerland",
    "DR": "Balkan Peninsula",
    "DS": "Asia",
    "DT": "Africa",
    "DU": "Oceania (South Seas). Australia. New Zealand",
    "DX": "Gypsies. Roma",
    // Class E: History of the Americas (General and United States)
    "E": "History of the Americas (General) and United States History",

    // Class F: History of the Americas (Local History of U.S., British, Dutch, French, Latin America)
    "F": "Local History of the United States; History of British, Dutch, French, and Latin America",

    // Class G: Geography, Anthropology, Recreation
    "G": "Geography (General). Atlases. Maps",
    "GA": "Mathematical geography. Cartography",
    "GB": "Physical geography",
    "GC": "Oceanography",
    "GE": "Environmental sciences",
    "GF": "Human ecology. Anthropogeography",
    "GN": "Anthropology",
    "GR": "Folklore",
    "GT": "Manners and customs (General)",
    "GV": "Recreation. Leisure",

    // Class H: Social Sciences
    "H": "Social sciences (General)",
    "HA": "Statistics",
    "HB": "Economic theory. Demography",
    "HC": "Economic history and conditions",
    "HD": "Economic history and conditions. Land use. Labor. Collective bargaining. Cooperatives. Environment. Etc.",
    "HE": "Transportation and communications",
    "HF": "Commerce",
    "HG": "Finance",
    "HJ": "Public finance",
    "HM": "Sociology (General)",
    "HN": "Social history and conditions. Social problems. Social reform",
    "HQ": "The family. Marriage. Women",
    "HS": "Societies: secret, benevolent, etc.",
    "HT": "Communities. Classes. Races",
    "HV": "Social pathology. Social and public welfare. Criminology",
    "HX": "Socialism. Communism. Anarchism",

    // Class J: Political Science
    "J": "Political science (General)",
    "JA": "Political science (General)",
    "JC": "Political theory",
    "JF": "Political institutions and public administration (General)",
    "JJ": "Political institutions and public administration (North America)",
    "JK": "Political institutions and public administration (United States)",
    "JL": "Political institutions and public administration (Canada, Latin America, etc.)",
    "JN": "Political institutions and public administration (Europe)",
    "JQ": "Political institutions and public administration (Asia, Africa, Australia, Pacific Area)",
    "JS": "Local government. Municipal government",
    "JV": "Colonies and colonization. Emigration and immigration. International migration",
    "JX": "International law, relations, etc.", // This class is largely superseded by JZ and K
    "JZ": "International relations",


// Class K: Law
    "K": "Law (General). Comparative and uniform law. Jurisprudence",
    "KB": "Religious law",
    "KBM": "Jewish law",
    "KBP": "Islamic law",
    "KBR": "History of Canon law",
    "KBU": "Law of the Roman Catholic Church. The Holy See",
    "KD": "Law of the United Kingdom and Ireland",
    "KDC": "Law of Scotland",
    "KDE": "Law of England and Wales",
    "KDG": "Law of Ireland",
    "KJE": "Law of the European Union",
    "KJG": "Law of Germany",
    "KJH": "Law of Italy",
    "KJJ": "Law of France",
    "KJK": "Law of the Netherlands",
    "KJM": "Law of Belgium. Law of Luxembourg",
    "KJN": "Law of Switzerland",
    "KJP": "Law of Spain. Law of Portugal",
    "KJR": "Law of Nordic countries",
    "KJS": "Law of Eastern Europe. Law of Russia",
    "KJT": "Law of the Soviet Union (former)",
    "KJV": "Law of Greece",
    "KJW": "Law of Turkey",
    "KJX": "Law of Cyprus",
    "KJU": "Law of Austria",
    "KJV": "Law of the Balkan States",
    "KK": "Law of Germany", // More specific to Germany
    "KL": "History of law (General)",
    "KM": "Private law",
    "KN": "Social law",
    "KO": "Public law",
    "KP": "Criminal law",
    "KQ": "Law of Asia (General)",
    "KR": "Law of Africa (General)",
    "KS": "Law of Australia and New Zealand",
    "KT": "Law of the Pacific Islands",
    "KU": "Law of Australia",
    "KV": "Law of New Zealand",
    "KW": "Law of Canada",
    "KWC": "Law of Quebec",
    "KWE": "Law of Ontario",
    "KWF": "Law of the Maritime Provinces",
    "KWG": "Law of the Prairie Provinces",
    "KWH": "Law of British Columbia",
    "KWL": "Law of Yukon, Northwest Territories, Nunavut",
    "KZ": "Law of nations. International law",
    "KZGD": "International criminal law",
    "KZI": "International trade law",
    "KZM": "International environmental law",
    "KZN": "Law of the sea",

    // Class L: Education
    "L": "Education (General)",
    "LA": "History of education",
    "LB": "Theory and practice of education",
    "LC": "Special aspects of education",
    "LD": "Individual institutions - United States",
    "LE": "Individual institutions - Americas (except U.S.)",
    "LF": "Individual institutions - Europe",
    "LG": "Individual institutions - Asia, Africa, Oceania",
    "LH": "College and school magazines and papers",
    "LJ": "Student fraternities and societies",
    "LT": "Textbooks",

    // Class M: Music
    "M": "Music",
    "ML": "Literature on music",
    "MT": "Musical instruction and study",

    // Class N: Fine Arts
    "N": "Fine arts (General)",
    "NA": "Architecture",
    "NB": "Sculpture",
    "NC": "Drawing. Design. Illustration",
    "ND": "Painting",
    "NE": "Print media. Printmaking and engraving",
    "NK": "Decorative arts. Applied arts. Decoration and ornament",
    "NX": "Arts in general",

    // Class P: Language and Literature
    "P": "Philology. Linguistics (General)",
    "PA": "Greek language and literature. Latin language and literature",
    "PB": "Modern European languages",
    "PC": "Romanic languages",
    "PD": "Germanic languages. Scandinavian languages",
    "PE": "English language",
    "PF": "West Germanic languages",
    "PG": "Slavic languages and literatures. Baltic languages. Albanian language",
    "PH": "Uralic languages. Basque language",
    "PJ": "Oriental languages and literatures",
    "PK": "Indo-Iranian languages and literatures",
    "PL": "Languages and literatures of Eastern Asia, Africa, Oceania",
    "PM": "Hyperborean languages. Native American languages. Artificial languages",
    "PN": "Literature (General)",
    "PQ": "French literature. Italian literature. Spanish literature. Portuguese literature",
    "PR": "English literature",
    "PS": "American literature",
    "PT": "German literature. Dutch literature. Scandinavian literatures",
    "PZ": "Fiction and juvenile belles lettres",

    // Class Q: Science
    "Q": "Science (General)",
    "QA": "Mathematics",
    "QB": "Astronomy",
    "QC": "Physics",
    "QD": "Chemistry",
    "QE": "Geology",
    "QH": "Natural history (General). Biology (General)",
    "QK": "Botany",
    "QL": "Zoology",
    "QM": "Human anatomy",
    "QP": "Physiology",
    "QR": "Microbiology",

    // Class R: Medicine
    "R": "Medicine (General)",
    "RA": "Public aspects of medicine",
    "RB": "Pathology",
    "RC": "Internal medicine",
    "RD": "Surgery",
    "RE": "Ophthalmology",
    "RF": "Otorhinolaryngology",
    "RG": "Gynecology and obstetrics",
    "RJ": "Pediatrics",
    "RK": "Dentistry",
    "RL": "Dermatology",
    "RM": "Pharmacology. Pharmacy. Materia medica",
    "RS": "Pharmacy and materia medica (General)",
    "RT": "Nursing",
    "RV": "Botanical, Thomsonian, and Eclectic medicine",
    "RX": "Homeopathy",
    "RZ": "Other systems of medicine",

    // Class S: Agriculture
    "S": "Agriculture (General)",
    "SB": "Plant culture",
    "SD": "Forestry",
    "SF": "Animal culture",
    "SH": "Aquaculture. Fisheries. Angling",
    "SK": "Hunting. Sports hunting. Trapping",

    // Class T: Technology
    "T": "Technology (General)",
    "TA": "Engineering (General). Civil engineering",
    "TC": "Hydraulic engineering. Ocean engineering",
    "TD": "Environmental technology. Sanitary engineering",
    "TE": "Highway engineering. Roads and pavements",
    "TF": "Railroad engineering and operation",
    "TG": "Bridge engineering",
    "TH": "Building construction",
    "TJ": "Mechanical engineering",
    "TK": "Electrical engineering. Electronics. Nuclear engineering",
    "TL": "Motor vehicles. Aeronautics. Astronautics",
    "TN": "Mining engineering. Metallurgy",
    "TP": "Chemical technology",
    "TR": "Photography",
    "TS": "Manufactures",
    "TT": "Handicrafts. Arts and crafts",
    "TX": "Home economics",

    // Class U: Military Science
    "U": "Military science (General)",
    "UA": "Armies: organization, distribution, military situation",
    "UB": "Military administration",
    "UC": "Military supplies and transportation",
    "UD": "Infantry",
    "UE": "Cavalry. Armor",
    "UF": "Artillery",
    "UG": "Military engineering. Air forces",
    "UH": "Other military services",

    // Class V: Naval Science
    "V": "Naval science (General)",
    "VA": "Navies: Organization, distribution, naval situation",
    "VB": "Naval administration",
    "VC": "Naval maintenance",
    "VD": "Naval seamen",
    "VE": "Naval marines",
    "VF": "Naval ordnance",
    "VG": "Minor naval services",
    "VK": "Navigation. Merchant marine",
    "VM": "Naval architecture. Shipbuilding. Marine engineering",

    // Class W: Medicine (Not used in the main Library of Congress system)
    // The W schedule is primarily for the National Library of Medicine classification,
    // which has its own detailed system (e.g., WA for Public Health, WB for Practice of Medicine).
    // The LoC uses R for medicine as seen above. So, traditionally, W is 'reserved' or not directly
    // part of the core LoC alphabet in the same way as other letters.

    // Class Z: Bibliography. Library Science. Information Resources (General)
    "Z": "Bibliography. Library science. Information resources (General)",
    "ZA": "Information resources (General)",
};

export const ddcClassifications = {
    "000": "Computer Science, Information & General Works",
    "100": "Philosophy & Psychology",
    "200": "Religion",
    "300": "Social Sciences",
    "400": "Language",
    "500": "Science",
    "600": "Technology & Applied Science",
    "700": "Arts & Recreation",
    "800": "Literature",
    "900": "History & Geography",
};


export const ddcSubclassifications = {
    // 000-099: Computer Science, Information & General Works
    "000": "Computer Science, Knowledge & General Works",
    "001": "Knowledge",
    "002": "The Book",
    "003": "Systems",
    "004": "Data Processing & Computer Science",
    "005": "Computer Programming, Programs & Data",
    "006": "Special Computer Methods",
    "007": "Not assigned or no longer used",
    "008": "Not assigned or no longer used",
    "009": "Not assigned or no longer used",
    "010": "Bibliography",
    "011": "Bibliographies",
    "012": "Bibliographies of individuals",
    "013": "Bibliographies of works by specific classes of authors",
    "014": "Bibliographies of anonymous and pseudonymous works",
    "015": "Bibliographies of works from specific places",
    "016": "Bibliographies of works on specific subjects",
    "017": "General subject catalogs",
    "018": "Catalogs arranged by author, date, etc.",
    "019": "Dictionary catalogs",
    "020": "Library & Information Sciences",
    "021": "Library relationships",
    "022": "Administration of physical plant",
    "023": "Personnel administration",
    "024": "Not assigned or no longer used",
    "025": "Library operations",
    "026": "Libraries for specific subjects",
    "027": "General libraries",
    "028": "Reading, use of other information media",
    "029": "Not assigned or no longer used",
    "030": "Encyclopedias & Books of Facts",
    "031": "Encyclopedias in American English",
    "032": "Encyclopedias in English",
    "033": "Encyclopedias in other Germanic languages",
    "034": "Encyclopedias in French, Occitan, Catalan",
    "035": "Encyclopedias in Italian, Romanian, Rhaeto-Romanic",
    "036": "Encyclopedias in Spanish & Portuguese",
    "037": "Encyclopedias in Slavic languages",
    "038": "Encyclopedias in Scandinavian languages",
    "039": "Encyclopedias in other languages",
    "040": "Not assigned or no longer used",
    "041": "Not assigned or no longer used",
    "042": "Not assigned or no longer used",
    "043": "Not assigned or no longer used",
    "044": "Not assigned or no longer used",
    "045": "Not assigned or no longer used",
    "046": "Not assigned or no longer used",
    "047": "Not assigned or no longer used",
    "048": "Not assigned or no longer used",
    "049": "Not assigned or no longer used",
    "050": "Magazines, Journals & Serials",
    "051": "American serials",
    "052": "Serials in English",
    "053": "Serials in other Germanic languages",
    "054": "Serials in French, Occitan, Catalan",
    "055": "Serials in Italian, Romanian, Rhaeto-Romanic",
    "056": "Serials in Spanish & Portuguese",
    "057": "Serials in Slavic languages",
    "058": "Serials in Scandinavian languages",
    "059": "Serials in other languages",
    "060": "Associations, Organizations & Museums",
    "061": "Organizations in North America",
    "062": "Organizations in British Isles, England",
    "063": "Organizations in central Europe, Germany",
    "064": "Organizations in France & Monaco",
    "065": "Organizations in Italy & adjacent islands",
    "066": "Organizations in Iberian Peninsula & adjacent islands",
    "067": "Organizations in eastern Europe, Russia",
    "068": "Organizations in other geographic areas",
    "069": "Museums",
    "070": "News Media, Journalism & Publishing",
    "071": "Newspapers in North America",
    "072": "Newspapers in British Isles, England",
    "073": "Newspapers in central Europe, Germany",
    "074": "Newspapers in France & Monaco",
    "075": "Newspapers in Italy & adjacent islands",
    "076": "Newspapers in Iberian Peninsula & adjacent islands",
    "077": "Newspapers in eastern Europe, Russia",
    "078": "Newspapers in Scandinavia",
    "079": "Newspapers in other geographic areas",
    "080": "Quotations",
    "081": "American quotations",
    "082": "Quotations in English",
    "083": "Quotations in other Germanic languages",
    "084": "Quotations in French, Occitan, Catalan",
    "085": "Quotations in Italian, Romanian, Rhaeto-Romanic",
    "086": "Quotations in Spanish & Portuguese",
    "087": "Quotations in Slavic languages",
    "088": "Quotations in Scandinavian languages",
    "089": "Quotations in other languages",
    "090": "Manuscripts & Rare Books",
    "091": "Manuscripts",
    "092": "Block books",
    "093": "Incunabula",
    "094": "Printed books",
    "095": "Books notable for bindings",
    "096": "Books notable for illustrations",
    "097": "Books notable for ownership or origin",
    "098": "Prohibited works, forgeries, hoaxes",
    "099": "Books notable for format",

    // 100-199: Philosophy & Psychology
    "100": "Philosophy & Psychology",
    "101": "Theory of philosophy",
    "102": "Miscellany of philosophy",
    "103": "Dictionaries of philosophy",
    "104": "Not assigned or no longer used",
    "105": "Serial publications of philosophy",
    "106": "Organizations & management of philosophy",
    "107": "Education, research, related topics of philosophy",
    "108": "Groups of people in philosophy",
    "109": "Historical treatment of philosophy",
    "110": "Metaphysics",
    "111": "Ontology",
    "112": "Not assigned or no longer used",
    "113": "Cosmology (Philosophy of nature)",
    "114": "Space",
    "115": "Time",
    "116": "Change",
    "117": "Structure",
    "118": "Force and energy",
    "119": "Number and quantity",
    "120": "Epistemology, Causation, Humankind",
    "121": "Epistemology (Theory of knowledge)",
    "122": "Causation",
    "123": "Determinism and indeterminism",
    "124": "Teleology",
    "125": "Not assigned or no longer used",
    "126": "The self",
    "127": "The unconscious and the subconscious",
    "128": "Humankind",
    "129": "Origin and destiny of individual souls",
    "130": "Paranormal Phenomena",
    "131": "Parapsychological and occult methods for achieving well-being",
    "132": "Not assigned or no longer used",
    "133": "Parapsychology and occultism",
    "134": "Not assigned or no longer used",
    "135": "Dreams and mysteries",
    "136": "Not assigned or no longer used",
    "137": "Divinatory graphology",
    "138": "Physiognomy",
    "139": "Phrenology",
    "140": "Specific Philosophical Schools",
    "141": "Idealism and related systems",
    "142": "Critical philosophy",
    "143": "Bergsonism and intuitionism",
    "144": "Humanism and related systems",
    "145": "Sensationalism",
    "146": "Naturalism and related systems",
    "147": "Pantheism and related systems",
    "148": "Eclecticism, liberalism, traditionalism",
    "149": "Other philosophical systems",
    "150": "Psychology",
    "151": "Not assigned or no longer used",
    "152": "Sensory perception, movement, emotions, drives",
    "153": "Conscious mental processes and intelligence",
    "154": "Subconscious and altered states",
    "155": "Differential and developmental psychology",
    "156": "Comparative psychology",
    "157": "Not assigned or no longer used",
    "158": "Applied psychology",
    "159": "Other aspects of psychology",
    "160": "Logic",
    "161": "Induction",
    "162": "Deduction",
    "163": "Not assigned or no longer used",
    "164": "Not assigned or no longer used",
    "165": "Fallacies and sources of error",
    "166": "Syllogisms",
    "167": "Hypotheses",
    "168": "Argument and persuasion",
    "169": "Analogy",
    "170": "Ethics (Moral Philosophy)",
    "171": "Ethical systems",
    "172": "Political ethics",
    "173": "Ethics of family relationships",
    "174": "Professional ethics",
    "175": "Ethics of recreation and leisure",
    "176": "Ethics of sex and reproduction",
    "177": "Ethics of social relations",
    "178": "Ethics of consumption",
    "179": "Other ethical norms",
    "180": "Ancient, Medieval, Eastern Philosophy",
    "181": "Eastern philosophy",
    "182": "Pre-Socratic Greek philosophies",
    "183": "Sophistic, Socratic, related philosophies",
    "184": "Platonic philosophy",
    "185": "Aristotelian philosophy",
    "186": "Skeptic and Neoplatonic philosophies",
    "187": "Epicurean philosophy",
    "188": "Stoic philosophy",
    "189": "Medieval western philosophy",
    "190": "Modern Western Philosophy",
    "191": "Philosophy of United States and Canada",
    "192": "Philosophy of British Isles",
    "193": "Philosophy of Germany and Austria",
    "194": "Philosophy of France",
    "195": "Philosophy of Italy",
    "196": "Philosophy of Spain and Portugal",
    "197": "Philosophy of Russia",
    "198": "Philosophy of Scandinavia",
    "199": "Philosophy of other geographic areas",

    // 200-299: Religion
    "200": "Religion",
    "201": "Religious sociology",
    "202": "Religious miscellany",
    "203": "Religious dictionaries",
    "204": "Not assigned or no longer used",
    "205": "Religious serial publications",
    "206": "Religious organizations",
    "207": "Religious education and research",
    "208": "Groups of religious people",
    "209": "Religious history and geography",
    "210": "Philosophy & Theory of Religion",
    "211": "Concepts of God",
    "212": "Existence, knowability, attributes of God",
    "213": "Creation",
    "214": "Theodicy",
    "215": "Science and religion",
    "216": "Not assigned or no longer used",
    "217": "Not assigned or no longer used",
    "218": "Humankind",
    "219": "Not assigned or no longer used",
    "220": "Bible",
    "221": "Old Testament",
    "222": "Historical books of Old Testament",
    "223": "Poetic books of Old Testament",
    "224": "Prophetic books of Old Testament",
    "225": "New Testament",
    "226": "Gospels and Acts",
    "227": "Epistles",
    "228": "Revelation (Apocalypse)",
    "229": "Apocrypha and pseudepigrapha",
    "230": "Christianity & Christian Denominations",
    "231": "God",
    "232": "Jesus Christ and his family",
    "233": "Humankind",
    "234": "Salvation and grace",
    "235": "Spiritual beings",
    "236": "Eschatology",
    "237": "Not assigned or no longer used",
    "238": "Creeds and confessions of faith",
    "239": "Apologetics and polemics",
    "240": "Christian Moral & Devotional Theology",
    "241": "Christian ethics",
    "242": "Devotional literature",
    "243": "Evangelistic writings for individuals",
    "244": "Not assigned or no longer used",
    "245": "Not assigned or no longer used",
    "246": "Use of art in Christianity",
    "247": "Church furnishings and related articles",
    "248": "Christian experience, practice, life",
    "249": "Christian observances in family life",
    "250": "Christian Orders & Local Church",
    "251": "Preaching",
    "252": "Texts of sermons",
    "253": "Pastoral office and work",
    "254": "Parish administration",
    "255": "Religious congregations and orders",
    "256": "Not assigned or no longer used",
    "257": "Not assigned or no longer used",
    "258": "Not assigned or no longer used",
    "259": "Pastoral care of families and groups",
    "260": "Christian Social Theology",
    "261": "Social theology",
    "262": "Ecclesiology",
    "263": "Days, times, places of religious observance",
    "264": "Public worship",
    "265": "Sacraments, other rites and acts",
    "266": "Missions",
    "267": "Associations for religious work",
    "268": "Religious education",
    "269": "Spiritual renewal",
    "270": "History of Christianity",
    "271": "Religious orders in church history",
    "272": "Persecutions in church history",
    "273": "Doctrinal controversies and heresies",
    "274": "History of Christianity in Europe",
    "275": "History of Christianity in Asia",
    "276": "History of Christianity in Africa",
    "277": "History of Christianity in North America",
    "278": "History of Christianity in South America",
    "279": "History of Christianity in other areas",
    "280": "Denominations & Sects of Christianity",
    "281": "Early church and Eastern churches",
    "282": "Roman Catholic Church",
    "283": "Anglican churches",
    "284": "Protestants of Continental origin",
    "285": "Presbyterian churches",
    "286": "Baptist churches",
    "287": "Methodist churches",
    "288": "Not assigned or no longer used",
    "289": "Other Christian denominations",
    "290": "Comparative Religion & Other Religions",
    "291": "Comparative religion",
    "292": "Classical religion",
    "293": "Germanic religion",
    "294": "Religions of Indic origin",
    "295": "Zoroastrianism",
    "296": "Judaism",
    "297": "Islam, Babism, Baha'i Faith",
    "298": "Not assigned or no longer used",
    "299": "Religions not provided for elsewhere",

    // 300-399: Social Sciences
    "300": "Social Sciences",
    "301": "Sociology and anthropology",
    "302": "Social interaction",
    "303": "Social processes",
    "304": "Factors affecting social behavior",
    "305": "Social groups",
    "306": "Culture and institutions",
    "307": "Communities",
    "308": "Not assigned or no longer used",
    "309": "Not assigned or no longer used",
    "310": "Collections of General Statistics",
    "311": "Not assigned or no longer used",
    "312": "Not assigned or no longer used",
    "313": "Not assigned or no longer used",
    "314": "General statistics of Europe",
    "315": "General statistics of Asia",
    "316": "General statistics of Africa",
    "317": "General statistics of North America",
    "318": "General statistics of South America",
    "319": "General statistics of other areas",
    "320": "Political Science (Politics & Government)",
    "321": "Systems of governments",
    "322": "Relation of state to organized groups",
    "323": "Civil and political rights",
    "324": "The political process",
    "325": "International migration and colonization",
    "326": "Slavery and emancipation",
    "327": "International relations",
    "328": "The legislative process",
    "329": "Not assigned or no longer used",
    "330": "Economics",
    "331": "Labor economics",
    "332": "Financial economics",
    "333": "Economics of land and energy",
    "334": "Cooperatives",
    "335": "Socialism and related systems",
    "336": "Public finance",
    "337": "International economics",
    "338": "Production",
    "339": "Macroeconomics and related topics",
    "340": "Law",
    "341": "Law of nations",
    "342": "Constitutional and administrative law",
    "343": "Military, defense, public property, public finance, tax, commerce, industrial law",
    "344": "Labor, social service, education, cultural law",
    "345": "Criminal law",
    "346": "Private law",
    "347": "Procedure and courts",
    "348": "Laws, regulations, cases",
    "349": "Law of specific jurisdictions",
    "350": "Public Administration & Military Science",
    "351": "Public administration",
    "352": "General considerations of public administration",
    "353": "Specific fields of public administration",
    "354": "Administration of economy and environment",
    "355": "Military science",
    "356": "Infantry forces",
    "357": "Mounted forces and warfare",
    "358": "Air and other specialized forces",
    "359": "Sea forces and warfare",
    "360": "Social Problems & Social Services",
    "361": "Social problems and social welfare in general",
    "362": "Social welfare problems and services",
    "363": "Other social problems and services",
    "364": "Criminology",
    "365": "Penal and related institutions",
    "366": "Association",
    "367": "General clubs",
    "368": "Insurance",
    "369": "Miscellaneous kinds of associations",
    "370": "Education",
    "371": "Schools and their activities; special education",
    "372": "Elementary education",
    "373": "Secondary education",
    "374": "Adult education",
    "375": "Curricula",
    "376": "Education of women",
    "377": "Schools and religion",
    "378": "Higher education",
    "379": "Public policy issues in education",
    "380": "Commerce, Communications & Transportation",
    "381": "Commerce (Trade)",
    "382": "International commerce (Foreign trade)",
    "383": "Postal communication",
    "384": "Communications; telecommunication",
    "385": "Railroad transportation",
    "386": "Inland waterway and ferry transportation",
    "387": "Water, air, space transportation",
    "388": "Transportation; ground transportation",
    "389": "Metrology and standardization",
    "390": "Customs & Folklore",
    "391": "Costume and personal appearance",
    "392": "Customs of life cycle and domestic life",
    "393": "Death customs",
    "394": "General customs",
    "395": "Etiquette (Manners)",
    "396": "Not assigned or no longer used",
    "397": "Not assigned or no longer used",
    "398": "Folklore",
    "399": "Customs of war and diplomacy",

    // 400-499: Language
    "400": "Language",
    "401": "Philosophy and theory of language",
    "402": "Miscellany of language",
    "403": "Dictionaries of language",
    "404": "Not assigned or no longer used",
    "405": "Serial publications of language",
    "406": "Organizations of language",
    "407": "Education, research, related topics of language",
    "408": "Groups of people in language",
    "409": "Geographic treatment of language",
    "410": "Linguistics",
    "411": "Writing systems",
    "412": "Etymology",
    "413": "Dictionaries",
    "414": "Phonology and phonetics",
    "415": "Grammar",
    "416": "Not assigned or no longer used",
    "417": "Dialectology and historical linguistics",
    "418": "Standard usage, applied linguistics",
    "419": "Sign languages",
    "420": "English & Old English (Anglo-Saxon)",
    "421": "English writing system and phonology",
    "422": "English etymology",
    "423": "English dictionaries",
    "424": "Not assigned or no longer used",
    "425": "English grammar",
    "426": "Not assigned or no longer used",
    "427": "English language variations",
    "428": "Standard English usage",
    "429": "Old English (Anglo-Saxon)",
    "430": "German & Related Languages",
    "431": "Writing systems and phonology German",
    "432": "Etymology of German",
    "433": "Dictionaries of German",
    "434": "Not assigned or no longer used",
    "435": "Grammar of German",
    "436": "Not assigned or no longer used",
    "437": "Variations of German",
    "438": "Standard usage of German",
    "439": "Other Germanic languages",
    "440": "French & Related Romance Languages",
    "441": "Writing systems and phonology of French",
    "442": "Etymology of French",
    "443": "Dictionaries of French",
    "444": "Not assigned or no longer used",
    "445": "Grammar of French",
    "446": "Not assigned or no longer used",
    "447": "Variations of French",
    "448": "Standard usage of French",
    "449": "Occitan and Catalan",
    "450": "Italian, Romanian & Related Romance Languages",
    "451": "Writing systems and phonology of Italian",
    "452": "Etymology of Italian",
    "453": "Dictionaries of Italian",
    "454": "Not assigned or no longer used",
    "455": "Grammar of Italian",
    "456": "Not assigned or no longer used",
    "457": "Variations of Italian",
    "458": "Standard usage of Italian",
    "459": "Romanian, Rhaeto-Romanic",
    "460": "Spanish & Portuguese Languages",
    "461": "Writing systems and phonology of Spanish",
    "462": "Etymology of Spanish",
    "463": "Dictionaries of Spanish",
    "464": "Not assigned or no longer used",
    "465": "Grammar of Spanish",
    "466": "Not assigned or no longer used",
    "467": "Variations of Spanish",
    "468": "Standard usage of Spanish",
    "469": "Portuguese",
    "470": "Latin & Italic Languages",
    "471": "Classical Latin writing and phonology",
    "472": "Classical Latin etymology",
    "473": "Classical Latin dictionaries",
    "474": "Not assigned or no longer used",
    "475": "Classical Latin grammar",
    "476": "Not assigned or no longer used",
    "477": "Old, postclassical, Vulgar Latin",
    "478": "Classical Latin usage",
    "479": "Other Italic languages",
    "480": "Hellenic Languages & Classical Greek",
    "481": "Classical Greek writing and phonology",
    "482": "Classical Greek etymology",
    "483": "Classical Greek dictionaries",
    "484": "Not assigned or no longer used",
    "485": "Classical Greek grammar",
    "486": "Not assigned or no longer used",
    "487": "Preclassical and postclassical Greek",
    "488": "Classical Greek usage",
    "489": "Other Hellenic languages",
    "490": "Other Languages",
    "491": "East Indo-European and Celtic languages",
    "492": "Afro-Asiatic languages; Semitic languages",
    "493": "Non-Semitic Afro-Asiatic languages",
    "494": "Altaic, Uralic, Hyperborean, Dravidian",
    "495": "Languages of East and Southeast Asia",
    "496": "African languages",
    "497": "North American native languages",
    "498": "South American native languages",
    "499": "Austronesian and other languages",

    // 500-599: Science
    "500": "Science",
    "501": "Philosophy and theory of science",
    "502": "Miscellany of science",
    "503": "Dictionaries of science",
    "504": "Not assigned or no longer used",
    "505": "Serial publications of science",
    "506": "Organizations of science",
    "507": "Education, research, related topics of science",
    "508": "Natural history",
    "509": "Historical and geographic treatment of science",
    "510": "Mathematics",
    "511": "General principles of mathematics",
    "512": "Algebra",
    "513": "Arithmetic",
    "514": "Topology",
    "515": "Analysis",
    "516": "Geometry",
    "517": "Not assigned or no longer used",
    "518": "Numerical analysis",
    "519": "Probabilities and applied mathematics",
    "520": "Astronomy",
    "521": "Celestial mechanics",
    "522": "Techniques, procedures, apparatus, equipment",
    "523": "Specific celestial bodies and phenomena",
    "524": "Not assigned or no longer used",
    "525": "Earth (Astronomical geography)",
    "526": "Mathematical geography",
    "527": "Celestial navigation",
    "528": "Ephemerides",
    "529": "Chronology",
    "530": "Physics",
    "531": "Classical mechanics; solid mechanics",
    "532": "Fluid mechanics; liquid mechanics",
    "533": "Pneumatics (Gas mechanics)",
    "534": "Sound and related vibrations",
    "535": "Light and related electromagnetic phenomena",
    "536": "Heat",
    "537": "Electricity and electronics",
    "538": "Magnetism",
    "539": "Modern physics",
    "540": "Chemistry",
    "541": "Physical chemistry",
    "542": "Techniques, procedures, apparatus, equipment",
    "543": "Analytical chemistry",
    "544": "Not assigned or no longer used",
    "545": "Not assigned or no longer used",
    "546": "Inorganic chemistry",
    "547": "Organic chemistry",
    "548": "Crystallography",
    "549": "Mineralogy",
    "550": "Earth Sciences & Geology",
    "551": "Geology, hydrology, meteorology",
    "552": "Petrology",
    "553": "Economic geology",
    "554": "Earth sciences of Europe",
    "555": "Earth sciences of Asia",
    "556": "Earth sciences of Africa",
    "557": "Earth sciences of North America",
    "558": "Earth sciences of South America",
    "559": "Earth sciences of other areas",
    "560": "Fossils & Prehistoric Life",
    "561": "Paleobotany; fossil microorganisms",
    "562": "Fossil invertebrates",
    "563": "Fossil marine and seashore invertebrates",
    "564": "Fossil mollusks and molluscoids",
    "565": "Fossil arthropods",
    "566": "Fossil chordates",
    "567": "Fossil cold-blooded vertebrates",
    "568": "Fossil birds",
    "569": "Fossil mammals",
    "570": "Biology",
    "571": "Physiology and related subjects",
    "572": "Biochemistry",
    "573": "Specific physiological systems in animals",
    "574": "Not assigned or no longer used",
    "575": "Specific parts of and physiological systems in plants",
    "576": "Genetics and evolution",
    "577": "Ecology",
    "578": "Natural history of organisms",
    "579": "Microorganisms, fungi, algae",
    "580": "Plants (Botany)",
    "581": "Specific topics in natural history of plants",
    "582": "Plants noted for specific vegetative characteristics",
    "583": "Dicotyledons",
    "584": "Monocotyledons",
    "585": "Gymnosperms",
    "586": "Seedless plants",
    "587": "Vascular seedless plants",
    "588": "Bryophytes",
    "589": "Not assigned or no longer used",
    "590": "Animals (Zoology)",
    "591": "Specific topics in natural history of animals",
    "592": "Invertebrates",
    "593": "Marine and seashore invertebrates",
    "594": "Mollusks and molluscoids",
    "595": "Arthropods",
    "596": "Chordates",
    "597": "Cold-blooded vertebrates; fishes",
    "598": "Birds",
    "599": "Mammals",

    // 600-699: Technology & Applied Science
    "600": "Technology & Applied Science",
    "601": "Philosophy and theory of technology",
    "602": "Miscellany of technology",
    "603": "Dictionaries of technology",
    "604": "Special topics of technology",
    "605": "Serial publications of technology",
    "606": "Organizations of technology",
    "607": "Education, research, related topics of technology",
    "608": "Inventions and patents",
    "609": "Historical and geographic treatment of technology",
    "610": "Medicine & Health",
    "611": "Human anatomy, cytology, histology",
    "612": "Human physiology",
    "613": "Personal health and safety",
    "614": "Forensic medicine; incidence of disease",
    "615": "Pharmacology and therapeutics",
    "616": "Diseases",
    "617": "Surgery and related medical specialties",
    "618": "Gynecology, obstetrics, pediatrics, geriatrics",
    "619": "Experimental medicine",
    "620": "Engineering",
    "621": "Applied physics",
    "622": "Mining and related operations",
    "623": "Military and nautical engineering",
    "624": "Civil engineering",
    "625": "Engineering of railroads and roads",
    "626": "Not assigned or no longer used",
    "627": "Hydraulic engineering",
    "628": "Sanitary engineering",
    "629": "Other branches of engineering",
    "630": "Agriculture",
    "631": "Techniques, apparatus, equipment, materials",
    "632": "Plant injuries, diseases, pests",
    "633": "Field and plantation crops",
    "634": "Orchards, fruits, forestry",
    "635": "Garden crops (Horticulture); vegetables",
    "636": "Animal husbandry",
    "637": "Processing dairy and related products",
    "638": "Insect culture",
    "639": "Hunting, fishing, conservation, related technologies",
    "640": "Home Economics & Family Living",
    "641": "Food and drink",
    "642": "Meals and table service",
    "643": "Housing and household equipment",
    "644": "Household utilities",
    "645": "Household furnishings",
    "646": "Sewing, clothing, personal living",
    "647": "Management of public households",
    "648": "Housekeeping",
    "649": "Child rearing; home care of people with disabilities",
    "650": "Management & Public Relations",
    "651": "Office services",
    "652": "Processes of written communication",
    "653": "Shorthand",
    "654": "Not assigned or no longer used",
    "655": "Not assigned or no longer used",
    "656": "Not assigned or no longer used",
    "657": "Accounting",
    "658": "General management",
    "659": "Advertising and public relations",
    "660": "Chemical Engineering",
    "661": "Industrial chemicals",
    "662": "Explosives, fuels, related products",
    "663": "Beverage technology",
    "664": "Food technology",
    "665": "Industrial oils, fats, waxes, gases",
    "666": "Ceramic and allied technologies",
    "667": "Cleaning, color, coating, related technologies",
    "668": "Technology of other organic products",
    "669": "Metallurgy",
    "670": "Manufacturing",
    "671": "Metalworking processes and primary metal products",
    "672": "Iron, steel, other iron alloys",
    "673": "Nonferrous metals",
    "674": "Lumber processing, wood products, cork",
    "675": "Leather and fur processing",
    "676": "Pulp and paper technology",
    "677": "Textiles",
    "678": "Elastomers and elastomer products",
    "679": "Other products of specific materials",
    "680": "Manufacture for Specific Uses",
    "681": "Precision instruments and other devices",
    "682": "Small forge work (Blacksmithing)",
    "683": "Hardware and household appliances",
    "684": "Furnishings and home workshops",
    "685": "Leather and fur goods, and related products",
    "686": "Printing and related activities",
    "687": "Clothing and accessories",
    "688": "Other final products, and packaging technology",
    "689": "Not assigned or no longer used",
    "690": "Building & Construction",
    "691": "Building materials",
    "692": "Auxiliary construction practices",
    "693": "Construction of specific materials and purposes",
    "694": "Wood construction; carpentry",
    "695": "Roof covering",
    "696": "Utilities",
    "697": "Heating, ventilating, air-conditioning",
    "698": "Detail finishing",
    "699": "Not assigned or no longer used",

    // 700-799: Arts & Recreation
    "700": "Arts & Recreation",
    "701": "Philosophy and theory of fine and decorative arts",
    "702": "Miscellany of fine and decorative arts",
    "703": "Dictionaries of fine and decorative arts",
    "704": "Special topics of fine and decorative arts",
    "705": "Serial publications of fine and decorative arts",
    "706": "Organizations and management of fine and decorative arts",
    "707": "Education, research, related topics of fine and decorative arts",
    "708": "Galleries, museums, private collections of fine and decorative arts",
    "709": "Historical and geographic treatment of fine and decorative arts",
    "710": "Landscaping & Area Planning",
    "711": "Area planning",
    "712": "Landscape architecture",
    "713": "Landscape architecture of trafficways",
    "714": "Water features in landscape architecture",
    "715": "Woody plants in landscape architecture",
    "716": "Herbaceous plants in landscape architecture",
    "717": "Structures in landscape architecture",
    "718": "Landscape architecture of cemeteries",
    "719": "Natural landscapes",
    "720": "Architecture",
    "721": "Architectural materials and structural elements",
    "722": "Architecture to ca. 300",
    "723": "Architecture from ca. 300 to 1399",
    "724": "Architecture from 1400",
    "725": "Public structures",
    "726": "Buildings for religious and related purposes",
    "727": "Buildings for education and research",
    "728": "Residential buildings",
    "729": "Design and decoration of structures and accessories",
    "730": "Sculpture",
    "731": "Processes, forms, subjects of sculpture",
    "732": "Sculpture to ca. 500",
    "733": "Greek, Etruscan, Roman sculpture",
    "734": "Sculpture from ca. 500 to 1399",
    "735": "Sculpture from 1400",
    "736": "Carving and carvings",
    "737": "Numismatics and sigillography",
    "738": "Ceramic arts",
    "739": "Art metalwork",
    "740": "Drawing & Decorative Arts",
    "741": "Drawing and drawings",
    "742": "Perspective in drawing",
    "743": "Drawing and drawings by subject",
    "744": "Not assigned or no longer used",
    "745": "Decorative arts",
    "746": "Textile arts",
    "747": "Interior decoration",
    "748": "Glass",
    "749": "Furniture and accessories",
    "750": "Painting",
    "751": "Techniques, procedures, apparatus, equipment, materials, forms",
    "752": "Color",
    "753": "Symbolism, allegory, mythology, legend",
    "754": "Genre paintings",
    "755": "Religion",
    "756": "Not assigned or no longer used",
    "757": "Human figures",
    "758": "Nature, architectural subjects and cityscapes",
    "759": "Historical and geographic treatment",
    "760": "Graphic Arts & Printmaking",
    "761": "Relief processes (Block printing)",
    "762": "Not assigned or no longer used",
    "763": "Lithographic (Planographic) processes",
    "764": "Chromolithography and serigraphy",
    "765": "Metal engraving",
    "766": "Mezzotinting, aquatinting, related processes",
    "767": "Etching and drypoint",
    "768": "Not assigned or no longer used",
    "769": "Prints",
    "770": "Photography, Computer Art, Film, Video",
    "771": "Techniques, procedures, apparatus, equipment, materials",
    "772": "Metallic salt processes",
    "773": "Pigment processes of printing",
    "774": "Holography",
    "775": "Digital photography",
    "776": "Computer art (Digital art)",
    "777": "Not assigned or no longer used",
    "778": "Fields and kinds of photography",
    "779": "Photographs",
    "780": "Music",
    "781": "General principles and musical forms",
    "782": "Vocal music",
    "783": "Music for single voices; the voice",
    "784": "Instruments and instrumental ensembles",
    "785": "Ensembles with one instrument per part",
    "786": "Keyboard and other instruments",
    "787": "Stringed instruments",
    "788": "Wind instruments",
    "789": "Not assigned or no longer used",
    "790": "Sports, Games & Entertainment",
    "791": "Public performances",
    "792": "Stage presentations",
    "793": "Indoor games and amusements",
    "794": "Indoor games of skill",
    "795": "Games of chance",
    "796": "Athletic and outdoor sports and games",
    "797": "Aquatic and air sports",
    "798": "Equestrian sports and animal racing",
    "799": "Fishing, hunting, shooting",
    "801": "Philosophy & theory of literature",
    "802": "Miscellany of literature",
    "803": "Dictionaries, encyclopedias, concordances of literature",
    "804": "Reserved (formerly for essays on general topics)",
    "805": "Serial publications of literature",
    "806": "Organizations & management of literature",
    "807": "Study & teaching of literature",
    "808": "Rhetoric & collections of literary texts",
    "808.001-.009": "Standard subdivisions of rhetoric & collections",
    "808.02": "Authorship (rhetoric)",
    "808.04": "Collections based on specific characteristics (e.g., genre, subject)",
    "808.1": "Rhetoric of poetry",
    "808.2": "Rhetoric of drama",
    "808.3": "Rhetoric of fiction",
    "808.4": "Rhetoric of essays",
    "808.5": "Rhetoric of public speaking",
    "808.6": "Rhetoric of letters",
    "808.7": "Rhetoric of humor & satire",
    "808.8": "Collections of literary texts",
    "808.81": "Collections of poetry",
    "808.82": "Collections of drama",
    "808.83": "Collections of fiction",
    "808.84": "Collections of essays",
    "808.85": "Collections of speeches",
    "808.86": "Collections of letters",
    "808.87": "Collections of humor & satire",
    "808.88": "Collections of miscellany",
    "809": "History, geographic treatment, biography of literature",
    "809.1": "History & criticism of poetry",
    "809.2": "History & criticism of drama",
    "809.3": "History & criticism of fiction",
    "809.4": "History & criticism of essays",
    "809.5": "History & criticism of speeches",
    "809.6": "History & criticism of letters",
    "809.7": "History & criticism of humor & satire",
    "809.8": "History & criticism of literary miscellany",
    "809.9": "History & criticism of specific aspects of literature",

    // 810-819: American literature in English
    "811": "American poetry in English",
    "812": "American drama in English",
    "813": "American fiction in English",
    "814": "American essays in English",
    "815": "American speeches in English",
    "816": "American letters in English",
    "817": "American humor, satire, parody in English",
    "818": "American miscellany in English",
    "819": "Reserved (e.g., for Canadian literature in English, though often classed with 810s or 820s)",

    // 820-829: English & Old English literatures
    "821": "English poetry",
    "822": "English drama",
    "823": "English fiction",
    "824": "English essays",
    "825": "English speeches",
    "826": "English letters",
    "827": "English humor, satire, parody",
    "828": "English miscellany",
    "829": "Old English (Anglo-Saxon) literature",

    // 830-839: Germanic literatures
    "831": "German poetry",
    "832": "German drama",
    "833": "German fiction",
    "834": "German essays",
    "835": "German speeches",
    "836": "German letters",
    "837": "German humor, satire, parody",
    "838": "German miscellany",
    "839": "Other Germanic literatures (e.g., Dutch, Afrikaans, Scandinavian, Icelandic)",

    // 840-849: French, Provençal, Catalan literatures
    "841": "French poetry",
    "842": "French drama",
    "843": "French fiction",
    "844": "French essays",
    "845": "French speeches",
    "846": "French letters",
    "847": "French humor, satire, parody",
    "848": "French miscellany",
    "849": "Provençal, Catalan, Franco-Provençal literatures",

    // 850-859: Italian, Romanian, Rhaeto-Romanic literatures
    "851": "Italian poetry",
    "852": "Italian drama",
    "853": "Italian fiction",
    "854": "Italian essays",
    "855": "Italian speeches",
    "856": "Italian letters",
    "857": "Italian humor, satire, parody",
    "858": "Italian miscellany",
    "859": "Romanian, Rhaeto-Romanic, Sardinian, Dalmatian literatures",

    // 860-869: Spanish & Portuguese literatures
    "861": "Spanish poetry",
    "862": "Spanish drama",
    "863": "Spanish fiction",
    "864": "Spanish essays",
    "865": "Spanish speeches",
    "866": "Spanish letters",
    "867": "Spanish humor, satire, parody",
    "868": "Spanish miscellany",
    "869": "Portuguese literature",

    // 870-879: Latin literatures
    "871": "Latin poetry",
    "872": "Latin dramatic poetry & drama",
    "873": "Latin epic poetry & fiction",
    "874": "Latin lyric poetry",
    "875": "Latin speeches",
    "876": "Latin letters",
    "877": "Latin humor, satire, parody",
    "878": "Latin miscellany",
    "879": "Reserved (e.g., Medieval Latin, Neo-Latin, though often classed with 870s)",

    // 880-889: Classical Greek literatures
    "881": "Classical Greek poetry",
    "882": "Classical Greek dramatic poetry & drama",
    "883": "Classical Greek epic poetry & fiction",
    "884": "Classical Greek lyric poetry",
    "885": "Classical Greek speeches",
    "886": "Classical Greek letters",
    "887": "Classical Greek humor, satire, parody",
    "888": "Classical Greek miscellany",
    "889": "Modern Greek literature",

    // 890-899: Other literatures (specific divisions for various world literatures)
    "891": "East Indo-European & Celtic literatures",
    "891.1": "Indic literatures",
    "891.2": "Sanskrit literature",
    "891.3": "Prakrit & Pali literatures",
    "891.4": "Modern Indic literatures",
    "891.5": "Iranian literatures",
    "891.6": "Celtic literatures",
    "891.7": "East Slavic literatures (Russian, Ukrainian, Belarusian)",
    "891.8": "Other Slavic literatures (Polish, Czech, Slovak, South Slavic)",
    "892": "Afro-Asiatic (Hamito-Semitic) literatures",
    "892.1": "Hebrew literature",
    "892.2": "Aramaic literature",
    "892.3": "Syriac literature",
    "892.4": "Arabic literature",
    "892.5": "Ethiopian literatures",
    "892.6": "Akkadian literature",
    "892.7": "Canaanite literatures",
    "893": "Non-Semitic Afro-Asiatic & Malayo-Polynesian literatures",
    "893.1": "Ancient Egyptian literature",
    "893.2": "Coptic literature",
    "893.3": "Berber literatures",
    "893.4": "Cushitic literatures",
    "893.5": "Chadic literatures",
    "893.6": "Malagasy literature",
    "893.7": "Indonesian (Malay) literatures",
    "893.8": "Philippine literatures",
    "893.9": "Other Malayo-Polynesian literatures",
    "894": "Ural-Altaic, Paleo-Siberian, Dravidian, other Asian literatures",
    "894.1": "Uralic literatures",
    "894.2": "Finnish literature",
    "894.3": "Hungarian literature",
    "894.4": "Altaic literatures",
    "894.5": "Turkic literatures",
    "894.6": "Mongolian literatures",
    "894.7": "Manchu-Tungus literatures",
    "894.8": "Dravidian literatures",
    "894.9": "Other Asian literatures",
    "895": "East Asian literatures",
    "895.1": "Chinese literature",
    "895.2": "Japanese literature",
    "895.3": "Korean literature",
    "895.4": "Tibetan literature",
    "895.5": "Burmese literature",
    "895.6": "Thai literature",
    "895.7": "Vietnamese literature",
    "895.8": "Other East Asian literatures",
    "896": "African literatures",
    "896.1": "Sudanic literatures",
    "896.2": "Bantu literatures",
    "896.3": "Swahili literature",
    "896.4": "Other African literatures",
    "897": "North American native literatures",
    "898": "South American native literatures",
    "899": "Other literatures (e.g., Artificial languages, Eskimo-Aleut, Austronesian, Oceanic, etc.)",
    "900": "History & Geography",
    "901": "Philosophy & theory of history",
    "902": "Miscellany of history",
    "903": "Dictionaries, encyclopedias, concordances of history",
    "904": "Collected accounts of events",
    "905": "Serial publications of history",
    "906": "Organizations & management of history",
    "907": "Study & teaching of history",
    "908": "History with respect to kinds of persons",
    "909": "World history",
    "909.04": "World history with respect to specific races & ethnic groups",
    "909.09": "World history with respect to specific conditions & situations",

    // 910-919: Geography & Travel
    "911": "Historical geography",
    "912": "Atlases, maps, globes",
    "913": "Geography of & travel in ancient world",
    "914": "Geography of & travel in Europe",
    "915": "Geography of & travel in Asia",
    "916": "Geography of & travel in Africa",
    "917": "Geography of & travel in North America",
    "918": "Geography of & travel in South America",
    "919": "Geography of & travel in other parts of world & extraterrestrial worlds; Pacific Ocean islands",

    // 920-929: Biography, Genealogy, Heraldry
    "920": "Biography, genealogy, heraldry",
    "921": "Biography of philosophers & psychologists (often used for collective biography of individuals with specific characteristics)",
    "929": "Genealogy, names, insignias",
    "929.1": "Genealogy",
    "929.2": "Family histories",
    "929.3": "Genealogical sources",
    "929.4": "Personal names",
    "929.5": "Inscriptions on tombs",
    "929.6": "Heraldry",
    "929.7": "Orders of knighthood & chivalry",
    "929.8": "Medals, badges, insignia",
    "929.9": "Flags, banners, standards",

    // 930-939: History of ancient world (to ca. 499 A.D.)
    "930": "History of ancient world (to ca. 499 A.D.)",
    "931": "Ancient China & Japan",
    "932": "Ancient Egypt",
    "933": "Ancient Palestine (Holy Land)",
    "934": "Ancient India",
    "935": "Ancient Mesopotamia & Iranian Plateau (Persia)",
    "936": "Ancient Europe north & west of Italy; Ancient Germany",
    "937": "Ancient Italy & adjacent territories; Ancient Rome",
    "938": "Ancient Greece",
    "939": "Other parts of ancient world",

    // 940-949: History of Europe
    "940": "History of Europe",
    "940.1": "Early history to 1453", // Medieval Europe
    "940.2": "1453-", // Modern Europe
    "940.3": "World War I",
    "940.4": "Military history of World War I",
    "940.5": "Mid-20th century, 1918-1945",
    "940.53": "World War II",
    "940.54": "Military history of World War II",
    "940.55": "Later 20th century, 1945-2000",
    "941": "History of Scotland & Ireland",
    "942": "History of England & Wales",
    "943": "History of Germany & Central Europe",
    "944": "History of France & Monaco",
    "945": "History of Italy & adjacent territories",
    "946": "History of Spain & Portugal",
    "947": "History of Eastern Europe; Russia",
    "948": "History of Scandinavia",
    "949": "History of other parts of Europe",

    // 950-959: History of Asia, Far East, Orient
    "950": "History of Asia, Far East, Orient",
    "951": "History of China & adjacent areas",
    "952": "History of Japan",
    "953": "History of Arabian Peninsula & adjacent areas",
    "954": "History of South Asia; India",
    "955": "History of Iran",
    "956": "History of Middle East (Near East)",
    "957": "History of Siberia (Asian Russia)",
    "958": "History of Central Asia",
    "959": "History of Southeast Asia",

    // 960-969: History of Africa
    "960": "History of Africa",
    "961": "History of Tunisia & Libya",
    "962": "History of Egypt & Sudan",
    "963": "History of Ethiopia & Eritrea",
    "964": "History of Morocco & Canary Islands",
    "965": "History of Algeria",
    "966": "History of West Africa & islands in Atlantic Ocean",
    "967": "History of Central Africa & islands in Indian Ocean",
    "968": "History of Southern Africa",
    "969": "History of islands in South Atlantic Ocean",

    // 970-979: History of North America
    "970": "History of North America",
    "970.004": "History of North American native peoples (specific ethnic groups)",
    "970.005": "History of North America by region or locality (e.g., Arctic, Caribbean)",
    "971": "History of Canada",
    "972": "History of Middle America; Mexico",
    "973": "History of United States",
    "973.1": "United States - Early history, to 1607",
    "973.2": "United States - Colonial period, 1607-1775",
    "973.3": "United States - Period of Revolution & Confederation, 1775-1789",
    "973.4": "United States - Constitutional period, 1789-1809",
    "973.5": "United States - 1809-1845 (Era of Good Feelings, Jacksonian Democracy)",
    "973.6": "United States - 1845-1861 (Mexican-American War, Kansas-Nebraska Act)",
    "973.7": "United States - Civil War, 1861-1865",
    "973.8": "United States - Reconstruction & late 19th century, 1865-1901",
    "973.9": "United States - 20th century & 21st century",
    "973.91": "United States - 1901-1953 (Progressive Era, World Wars)",
    "973.92": "United States - 1953-2001 (Cold War, Civil Rights, Vietnam)",
    "973.93": "United States - 2001-",
    "974": "History of Northeastern United States",
    "975": "History of Southeastern United States",
    "976": "History of South Central United States",
    "977": "History of North Central United States",
    "978": "History of Western United States",
    "979": "History of Great Basin & Pacific Coast regions of United States; Alaska, Hawaii",

    // 980-989: History of South America
    "980": "History of South America",
    "981": "History of Brazil",
    "982": "History of Argentina",
    "983": "History of Chile",
    "984": "History of Bolivia",
    "985": "History of Peru",
    "986": "History of Colombia & Ecuador",
    "987": "History of Venezuela",
    "988": "History of Guiana",
    "989": "History of Paraguay & Uruguay",

    // 990-999: History of other parts of world; of extraterrestrial worlds; Pacific Ocean islands
    "990": "History of other parts of world; of extraterrestrial worlds; Pacific Ocean islands",
    "993": "History of New Zealand",
    "994": "History of Australia",
    "995": "History of Melanesia (New Guinea & adjacent islands)",
    "996": "History of Polynesia & Micronesia",
    "997": "History of Atlantic Ocean islands",
    "998": "History of Arctic islands & Antarctica",
    "999": "History of extraterrestrial worlds; Interplanetary journeys",

};