import React from "react";

const Article = () => {
    return (
        <div className="uHero-cont">
            <section className="userHero relative mt-2 mb-4">
                <div className="absolute inset-0">
                    <img 
                        src="image/bg-hero.png" 
                        alt="Hero Background" 
                        className="w-full h-full object-cover rounded-lg" // Add rounded-lg here
                    />
                </div>
                
            </section>
            <h1 className="font-semibold text-4xl mb-2.5">Celebrating World Mental Health Day</h1>
            <p className="text-a-t-red font-semibold mb-2.5">October 10, 2024</p>
            <p className="mb-2.5 text-justify">
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            <br />
            <br />
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            <br />
            <br />
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            <br />
            <br />
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            Today, we celebrate the power of nurturing our mental well-being. Explore books that offer... 
            </p>

        </div>
    );
}
export default Article;
